import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{Activity,AlertTriangle,BarChart3,Bell,Camera,Check,ChevronRight,Clock3,Cpu,Download,Eye,LayoutDashboard,Radio,RefreshCw,Search,Settings,ShieldAlert,SlidersHorizontal,Video,Wifi,WifiOff,X}from'lucide-react';import'./styles.css';

type Dashboard={cameras:{total:number,online:number},events24h:number,critical_unacked:number,avg_fps:number,avg_latency_ms:number,gpu_load:number,precision:number,recall:number,trend:{label:string,value:number}[]};
type Cam={id:string,name:string,zone:string,status:string,fps:number,latency_ms:number,enabled:number};
type Event={id:number,timestamp:string,camera_id:string,camera_name:string,zone:string,type:string,severity:string,confidence:number,person_id:string,acknowledged:number};
const labels:Record<string,string>={no_helmet:'Без каски',no_vest:'Без жилета',phone_usage:'Телефон',smoking:'Курение',restricted_zone:'Опасная зона',immobility:'Неподвижность'};
const api=async<T,>(url:string,opts?:RequestInit):Promise<T>=>{const r=await fetch(url,opts);if(!r.ok)throw new Error(await r.text());return r.json()};
function Spark({data}:{data:{label:string,value:number}[]}){const max=Math.max(...data.map(x=>x.value),1);return <div className="spark">{data.map((x,i)=><div key={i} className="barwrap"><div className="bar" style={{height:`${Math.max(8,x.value/max*100)}%`}}/><span>{i%2===0?x.label:''}</span></div>)}</div>}
function App(){const[tab,setTab]=useState('Обзор');const[d,setD]=useState<Dashboard|null>(null);const[cams,setCams]=useState<Cam[]>([]);const[events,setEvents]=useState<Event[]>([]);const[loading,setLoading]=useState(true);const[toast,setToast]=useState('');const load=async()=>{setLoading(true);try{const[a,b,c]=await Promise.all([api<Dashboard>('/api/dashboard'),api<Cam[]>('/api/cameras'),api<Event[]>('/api/events?limit=30')]);setD(a);setCams(b);setEvents(c)}finally{setLoading(false)}};useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);const ack=async(id:number)=>{await api(`/api/events/${id}/ack`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{"note":"Проверено оператором"}'});setEvents(v=>v.map(e=>e.id===id?{...e,acknowledged:1}:e));setToast('Событие подтверждено');setTimeout(()=>setToast(''),2200)};const simulate=async()=>{await api('/api/events/simulate',{method:'POST'});await load();setToast('Тестовое событие получено');setTimeout(()=>setToast(''),2200)};
 const nav=[['Обзор',LayoutDashboard],['Камеры',Video],['События',ShieldAlert],['Модели',Cpu],['Настройки',Settings]] as const;const content=tab==='Камеры'?<Cameras cams={cams}/>:tab==='События'?<Events events={events} ack={ack}/>:tab==='Модели'?<Models/>:tab==='Настройки'?<Config/>:<Overview d={d} cams={cams} events={events} ack={ack}/>;
 return <div className="app"><aside><div className="brand"><div className="brandmark"><Eye size={22}/></div><div><b>ZMK VISION</b><small>Центр видеоаналитики</small></div></div><nav>{nav.map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I size={19}/><span>{n}</span>{n==='События'&&d?.critical_unacked?<em>{d.critical_unacked}</em>:null}</button>)}</nav><div className="side-status"><div><span className="pulse"/> Система работает</div><small>Версия 1.0.0 • On-premise</small></div><div className="profile"><div className="avatar">АП</div><div><b>Алексей Петров</b><small>Администратор</small></div><ChevronRight size={16}/></div></aside><main><header><div><h1>{tab}</h1><p>Производственная безопасность в реальном времени</p></div><div className="head-actions"><div className="search"><Search size={17}/><span>Поиск</span><kbd>⌘ K</kbd></div><button className="icon"><Bell size={19}/><i/></button><button className="refresh" onClick={load}><RefreshCw className={loading?'spin':''} size={17}/> Обновить</button></div></header><section>{content}</section></main><button className="fab" onClick={simulate}><Radio size={18}/> Тест события</button>{toast&&<div className="toast"><Check size={17}/>{toast}</div>}</div>}
function Metric({icon:I,label,value,unit,accent,delta}:{icon:any,label:string,value:string|number,unit?:string,accent:string,delta:string}){return <article className="metric"><div className={`mi ${accent}`}><I size={21}/></div><div className="metric-top"><span>{label}</span><b>{value}<small>{unit}</small></b></div><div className="delta"><Activity size={13}/>{delta}</div></article>}
function Overview({d,cams,events,ack}:{d:Dashboard|null,cams:Cam[],events:Event[],ack:(id:number)=>void}){if(!d)return <div className="loader"/>;return <><div className="statusline"><div><span className="pulse"/><b>Все ключевые сервисы работают штатно</b><span>Последняя проверка: только что</span></div><button>Диагностика <ChevronRight size={15}/></button></div><div className="metrics"><Metric icon={Camera} label="Камеры онлайн" value={`${d.cameras.online}/${d.cameras.total}`} accent="green" delta="Стабильно за 24 часа"/><Metric icon={ShieldAlert} label="События за 24 ч" value={d.events24h} accent="amber" delta="Требуют внимания: 7"/><Metric icon={AlertTriangle} label="Критические" value={d.critical_unacked} accent="red" delta="Неподтверждённые"/><Metric icon={Cpu} label="Загрузка GPU" value={d.gpu_load} unit="%" accent="blue" delta="Температура 63 °C"/></div><div className="grid"><article className="panel trend"><PanelTitle title="Динамика событий" sub="Последние 12 часов" action="Все метрики"/><Spark data={d.trend}/><div className="legend"><span><i className="orange"/>Нарушения СИЗ</span><span><i className="red-dot"/>Критические</span><b>{d.avg_fps} FPS <small>среднее</small></b></div></article><article className="panel health"><PanelTitle title="Качество аналитики" sub="Активная модель siz-guard-v2.1"/><div className="quality"><Ring value={d.precision} label="Precision"/><Ring value={d.recall} label="Recall"/></div><div className="latency"><Clock3 size={17}/><span>Средняя задержка</span><b>{d.avg_latency_ms} мс</b></div></article></div><div className="grid lower"><article className="panel"><PanelTitle title="Последние события" sub="Обновляется автоматически" action="Все события"/><EventsTable events={events.slice(0,5)} ack={ack}/></article><article className="panel"><PanelTitle title="Статус камер" sub={`${d.cameras.online} из ${d.cameras.total} подключены`} action="Все камеры"/><div className="camlist">{cams.slice(0,5).map(c=><div className="camrow" key={c.id}><div className="thumb"><Camera size={18}/><span className={c.status}/></div><div><b>{c.name}</b><small>{c.zone}</small></div><div className="cammetric"><b>{c.status==='online'?`${c.fps} FPS`:'Нет сигнала'}</b><small>{c.status==='online'?`${c.latency_ms} мс`:'Проверьте RTSP'}</small></div><div className={`tag ${c.status}`}>{c.status==='online'?<Wifi size={12}/>:<WifiOff size={12}/>} {c.status==='online'?'Онлайн':'Офлайн'}</div></div>)}</div></article></div></>}
function PanelTitle({title,sub,action}:{title:string,sub:string,action?:string}){return <div className="pt"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button>{action}<ChevronRight size={14}/></button>}</div>}
function Ring({value,label}:{value:number,label:string}){return <div className="ringbox"><div className="ring" style={{'--p':`${value*3.6}deg`} as React.CSSProperties}><span>{value}<small>%</small></span></div><b>{label}</b><small>Цель ≥ {label==='Precision'?90:85}%</small></div>}
function EventsTable({events,ack}:{events:Event[],ack:(id:number)=>void}){return <div className="table"><div className="tr th"><span>Событие</span><span>Камера / зона</span><span>Уверенность</span><span>Время</span><span/></div>{events.map(e=><div className="tr" key={e.id}><span><i className={`sev ${e.severity}`}/><b>{labels[e.type]||e.type}</b><small>{e.person_id}</small></span><span><b>{e.camera_name||e.camera_id}</b><small>{e.zone}</small></span><span><b>{Math.round(e.confidence*100)}%</b><small className="conf"><i style={{width:`${e.confidence*100}%`}}/></small></span><span><b>{new Date(e.timestamp).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</b><small>{new Date(e.timestamp).toLocaleDateString('ru-RU')}</small></span><span>{e.acknowledged?<span className="done"><Check size={13}/> Принято</span>:<button className="ack" onClick={()=>ack(e.id)}>Принять</button>}</span></div>)}</div>}
function Cameras({cams}:{cams:Cam[]}){return <div className="cards">{cams.map(c=><article className="camera-card"><div className="feed"><Camera size={32}/><span className={`live ${c.status}`}>{c.status==='online'?'● LIVE':'OFFLINE'}</span><b>{c.id}</b></div><div className="camera-info"><div><h3>{c.name}</h3><p>{c.zone}</p></div><span className={`tag ${c.status}`}>{c.status==='online'?'Онлайн':'Офлайн'}</span></div><div className="camera-stats"><span>FPS <b>{c.fps}</b></span><span>Latency <b>{c.latency_ms} ms</b></span><span>AI <b>{c.enabled?'ON':'OFF'}</b></span></div></article>)}</div>}
function Events({events,ack}:{events:Event[],ack:(id:number)=>void}){return <article className="panel full"><div className="toolbar"><div><h3>Журнал событий</h3><p>{events.length} последних детекций</p></div><div><button><SlidersHorizontal size={16}/> Фильтры</button><a href="/api/reports/events.csv"><Download size={16}/> Экспорт CSV</a></div></div><EventsTable events={events} ack={ack}/></article>}
function Models(){return <div className="model-grid"><article className="panel model active-model"><span>АКТИВНА</span><Cpu size={32}/><h2>siz-guard-v2.1</h2><p>TensorRT • YOLOv8 • FP16</p><div><b>92.4%<small>Precision</small></b><b>87.1%<small>Recall</small></b><b>8.7<small>FPS / поток</small></b></div><button><Check size={16}/> Используется</button></article><article className="panel model"><Cpu size={32}/><h2>siz-guard-v2.0</h2><p>ONNX • YOLOv8 • FP32</p><div><b>90.8%<small>Precision</small></b><b>85.9%<small>Recall</small></b><b>6.4<small>FPS / поток</small></b></div><button>Активировать</button></article></div>}
function Config(){const vals=[['Каска','0.85'],['Сигнальный жилет','0.80'],['Использование телефона','0.78']];return <article className="panel config"><PanelTitle title="Пороги детекции" sub="Настройте минимальную уверенность модели"/>{vals.map(([n,v])=><label><span><b>{n}</b><small>Confidence threshold</small></span><input type="range" min="10" max="100" defaultValue={+v*100}/><output>{v}</output></label>)}<button>Сохранить изменения</button></article>}
createRoot(document.getElementById('root')!).render(<App/>);
